[2024-08-12 22:41:24,225] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_folder scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-12 22:41:24,232] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_first_dag.create_folder scheduled__2024-08-12T00:00:00+00:00 [queued]>
[2024-08-12 22:41:24,233] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-12 22:41:24,233] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-08-12 22:41:24,233] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-12 22:41:24,247] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): create_folder> on 2024-08-12 00:00:00+00:00
[2024-08-12 22:41:24,251] {standard_task_runner.py:52} INFO - Started process 6668 to run task
[2024-08-12 22:41:24,262] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'create_folder', 'scheduled__2024-08-12T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpxd11yzj8', '--error-file', '/tmp/tmp14hqbsul']
[2024-08-12 22:41:24,263] {standard_task_runner.py:80} INFO - Job 29: Subtask create_folder
[2024-08-12 22:41:24,313] {task_command.py:370} INFO - Running <TaskInstance: my_first_dag.create_folder scheduled__2024-08-12T00:00:00+00:00 [running]> on host kaiwangairflow
[2024-08-12 22:41:24,357] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=my_first_dag
AIRFLOW_CTX_TASK_ID=create_folder
AIRFLOW_CTX_EXECUTION_DATE=2024-08-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-12T00:00:00+00:00
[2024-08-12 22:41:24,359] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-08-12 22:41:24,359] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/kai/Documents/airflowalura/new_folder"']
[2024-08-12 22:41:24,367] {subprocess.py:85} INFO - Output:
[2024-08-12 22:41:24,368] {subprocess.py:96} INFO - Command exited with return code 0
[2024-08-12 22:41:24,384] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=my_first_dag, task_id=create_folder, execution_date=20240812T000000, start_date=20240813T014124, end_date=20240813T014124
[2024-08-12 22:41:24,432] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-08-12 22:41:24,446] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
